
server.servlet.session.persistent=true
#server.servlet.session.cookie.same-site=None
#   Si HTTPS, mettre true !
#server.servlet.session.cookie.secure=false  
#server.servlet.session.tracking-modes=cookie


spring:
  profiles:
    active: prod  # switch to "dev" for development
